In [40]:
#from lecture 4
class Layer_Dense:
    def __init__(self, inputs, neurons):
        self.weight = 0.01*np.random.randn(inputs, neurons)
        self.biases = np.zeros((1, neurons))

    def forwardpass(self, inputs):
        self.output = np.dot(inputs, self.weight) + self.biases

In [41]:
import numpy as np
inputs = [2, -5, 6, 0, 3, -0.5]
output = np.maximum(0, inputs)#implementation of ReLu
print(output)

[2. 0. 6. 0. 3. 0.]


In [42]:
# Relu activation
class Activation_ReLu:
    #forward pass
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
        

In [43]:
from nnfs.datasets import spiral_data
import nnfs
nnfs.init()
X, y = spiral_data(samples = 100, classes=3)

dense1 = Layer_Dense(2,3)

activation1 = Activation_ReLu()

dense1.forwardpass(X)

activation1.forward(dense1.output)

print(activation1.output[:5])

[[0.         0.         0.        ]
 [0.         0.00011395 0.        ]
 [0.         0.00031729 0.        ]
 [0.         0.00052666 0.        ]
 [0.         0.00071401 0.        ]]


In [ ]:
##Activation function : Softmax

In [46]:
inputs = [[1, 2, 3, 2.5],
          [4, 2, 3, 6],
          [1, 2, 7, 9]]
expo_values = np.exp(inputs - np.max(inputs, axis=1, keepdims = True))
probabilities = expo_values / np.sum(expo_values, axis = 1, keepdims = True)
print(probabilities)
np.sum(probabilities, axis=1)

[[6.41476854e-02 1.74371488e-01 4.73990846e-01 2.87489981e-01]
 [1.12457214e-01 1.52194289e-02 4.13706969e-02 8.30952661e-01]
 [2.95150233e-04 8.02301516e-04 1.19072103e-01 8.79830446e-01]]


array([1., 1., 1.])

In [49]:
#Softmax activation
class Activation_softmax:
    #forward pass
    def forward(self, inputs):
        expo_values = np.exp(inputs - np.max(inputs, axis= 1, keepdims= True))

        probabilities = expo_values / np.sum(expo_values, axis = 1, keepdims = True)

        self.output = probabilities

In [50]:
#create dataset
from nnfs.datasets import spiral_data
import nnfs
nnfs.init()
s, y = spiral_data(samples=100, classes=3)

dense01 = Layer_Dense(2,3)
activation1 = Activation_ReLu()
dense02 = Layer_Dense(3,3)
activation2 = Activation_softmax()

dense01.forwardpass(s)
activation1.forward(dense01.output)
dense02.forwardpass(activation1.output)
activation2.forward(dense02.output)
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
