In [15]:
#Array Summation in python
import numpy as np
Array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (np.sum(Array1))
print(np.sum(Array1, axis = None))
print(np.sum(Array1, axis= 0))
print(np.sum(Array1, axis= 1))
print(np.sum(Array1, axis= 0, keepdims = True)) # column wise
print(np.sum(Array1, axis= 1, keepdims = True)) # row wise

45
45
[12 15 18]
[ 6 15 24]
[[12 15 18]]
[[ 6]
 [15]
 [24]]


In [20]:
#Application of Array broadcasting 
Array2 = np.max(Array1, axis = 1,, keepdims = True)
print(Array2)

print(Array1 - Array2)

[3 6 9]
[[-2 -4 -6]
 [ 1 -1 -3]
 [ 4  2  0]]
